services:
  papi-app:
    build: .
    container_name: api-papi
    ports:
      - "8089:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    networks:
      - papi-network
      - mysql_network

networks:
  papi-network:
    external: true
  mysql_network:
    external: true