# Dev-only overrides

spring.devtools.restart.enabled=${DEVTOOLS_RESTART_ENABLED:true}

# Verbose SQL for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Friendly logging
logging.level.org.antredesloutres.papi=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Auto-update schema in dev (NEVER use in prod)
spring.jpa.hibernate.ddl-auto=update
